(add-to-list 'load-path (file-name-directory (or load-file-name buffer-file-name)))
(load "extended/mode-line.el" nil t)
(load "extended/org-mode.el" nil t)
(load "extended/spell-check.el" nil t)
(load "extended/editing-config.el" nil t)
(load "extended/dired-setting.el" nil t)
(load "extended/git.el" nil t)
(load "extended/multiple-cursors.el" nil t)
(load "extended/buffer-completion-system.el" nil t)
(load "extended/minibuffer-completion-system.el" nil t)
(load "extended/more-packages.el" nil t)
